= xBRL Granular Data (xBRL-GD)

== Semantic model definition

source/20230207_ADCS_SemanticLogicalHierarchic_Nobu.xlsx

[headers,cols="1,1"]
|===
^|sheet ^|content 

|ADCS_SemanticLogicalHierarchicy
|Original sheet provided by Mr J Vrijenhoek.

|ADCS_SemanticLogical +
Object class sheet
|Object class definition based on the extended Core component technical specification (Revised CCTS).

|ADCS_H +
Logical Hierarchy sheet
|Revised definition based on the Revised CCTS for ADCS_SemanticLogicalHierarchicy

|===

== xBRL-CSV taxonomy creation

=== Object class sheet

ADCS_C2xBRL-taxonomy.py

"args": ["source/ADCS_C.csv","-e utf-8","-d","-v"]

Created xBRL taxonomy stored under taxonomy/C

=== Logical Hierarchy sheet

ADCS_H2xBRL-taxonomy.py

"args": ["source/ADCS_H.csv","-e utf-8","-d","-v"]

Created xBRL taxonomy stored under taxonomy/H

== xBRL-CSV instance creation

=== source XBRL-GL based spread sheet

instance/xbrl-instances.csv

instance/xbrl-instances0_H.csv (Partial)

=== From Object class definition

TBD

=== From Logical Hierarchy definition

instance/CSV_H2OIM.py

Converted CSV +
instance/adc-instances0_H.csv

Meta file for xBRL-CSV +
instance/adc-instances0_H.json

== 

'd_GL02','d_GL03','d_BS01','GL02-001','GL02-002','GL02-005','GL02-006','GL02-007','GL03-001','GL03-002','GL03-003','GL03-004','GL03-005','GL03-006','GL03-007','BS09-001','BS09-002','BS09-003','BS09-005','BS09-006','BS09-007','CM07-001','CM08-001','CM01-001','CM01-002','BS01-001','BS01-002','BS01-004'