tablesMap = {
'Business Segment': 'PE72',
'Business Segment Hierarchy': 'BS02',
'Employee': 'BS03',
'User': 'BS04',
'Customer Type': 'BS05',
'Customer': 'BS06',
'Physical Address': 'NV51',
'Billing Address': 'BS58',
'Primary Contact': 'BS59',
'Created': 'PE69',
'Approved': 'PE70',
'Last Modified': 'PE71',
'Supplier Type': 'BS07',
'Supplier': 'BS08',
'Chart Of Accounts': 'BS09',
'Accounting Period': 'BS10',
'Journal Entry Type': 'BS11',
'Bill Type': 'BS12',
'Settlement Method': 'BS13',
'Currency': 'GL65',
'Measurement Unit': 'BS15',
'Payment Term': 'BS16',
'Project': 'BS17',
'Bank Account': 'BS18',
'Tax Regulatory': 'BS19',
'Tax Type': 'BS20',
'Customized Account Segment': 'BS21',
'Customized Account Value': 'BS22',
'Profile': 'BS23',
'Gl Trial Balance': 'GL01',
'Beginning Balance': 'GL63',
'Ending Balance': 'GL64',
'Gl Header': 'GL02',
'Gl Details': 'GL68',
'Amount': 'AP56',
'Posted': 'NV61',
'Account Segment': 'GL66',
'Gl Source': 'GL03',
'Gl Account Segment': 'GL04',
'Gl Account Period Balance': 'GL05',
'Debit Amount': 'GL61',
'Credit Amount': 'GL62',
'Open Account Receivable': 'AR01',
'Balance': 'SL78',
'Cash Received': 'AR02',
'AR Cash Application': 'AR03',
'AR Adjustment': 'AR04',
'Adjustment Amount': 'AP68',
'Tax': 'PR74',
'Ar Adjustment Details': 'AR70',
'Sales Contract': 'SL01',
'Sales Contract Details': 'SL54',
'Sales Order': 'SL02',
'Sales Order Details': 'SL71',
'Sales Invoice Generated': 'SL04',
'Sales Invoice Generated Details': 'SL68',
'Sales Shipment Made': 'SL05',
'Sales Shipment Made Details': 'SL75',
'Ap Open Account Payable': 'SL06',
'Ap Payment Made': 'AP01',
'Ap Cash Application': 'AP02',
'Ap Adjustment': 'AP03',
'Ap Adjustment Details': 'AP67',
'Purchase Requisition': 'PR01',
'Purchase Requisition Details': 'PR53',
'Purchase Contract': 'PR02',
'Purchase Contract Details': 'PR58',
'Purchase Order': 'PR03',
'Purchase Order Details': 'PR65',
'Purchase Invoice Received': 'PR04',
'Purchase Invoice Received Details': 'PR73',
'Purchase Materials Received': 'PR05',
'Purchase Materials Received Details': 'PR80',
'Inventory Location': 'NV01',
'Inventory Product Type': 'NV02',
'Inventory Product': 'NV03',
'Inventory On Hand': 'NV04',
'Inventory Transaction': 'NV05',
'Inventory Physical Inventory': 'NV06',
'Inventory Period Balance': 'NV07',
'Property Plant and Equipment Type': 'PE01',
'PPE Type': 'PE01',
'Property Plant and Equipment Master': 'PE02',
'PPE Master': 'PE02',
'Property Plant and Equipment Addition': 'PE03',
'PPE Addition': 'PE03',
'Property Plant and Equipment Removal': 'PE04',
'PPE Removal': 'PE04',
'Property Plant and Equipment Change': 'PE05',
'PPE Change': 'PE05',
'PPE Department Allocation': 'PE06',
'Property Plant and Equipment Department Allocation': 'PE06',
'Property Plant and Equipment Depreciation Method': 'PE07',
'PPE Depreciation': 'PE08',
'Property Plant and Equipment Depreciation': 'PE08',
'Selection Period': 'CM01',
'Gl Details Char': 'CM02',
'Sales Invoice Details Characteristics': 'CM03',
'Purchase Invoice Details Characteristics': 'CM04',
'Inventory Product Characteristics': 'CM05',
'Inventory Transaction Characteristics': 'CM06',
'Inventory Transaction Associated Document': 'CM07',
'GRFR Report Header': 'GF01',
'GRFR Report Body': 'GF02',
'Payroll Period': 'PR01',
'Payroll Item': 'PR02',
'Payslip': 'PR03',
'Payslip Detail': 'PR51'
}
